name: Almaeventos

# Aqui indicaremos el nombre de la rama sobre la cual al hacer push se iniciara el proceso de despliegue automatico
on:
  push:
    branches:
      - deploy_almaeventos

jobs:
  Docker:
    if: ${{ github.ref_name == 'deploy_almaeventos' }} && ${{vars.ORGANIZATION_VAR == 'yeboyebo'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "yeboyebo/quimera-olula"
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12
      - name: Make envfile
        run: echo "VITE_API_URL=https://api.aeproducciones.es" > .env && echo "VITE_API_URL=https://api.aeproducciones.es" > ./apps/almaeventos/.env

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependecies
        run: pnpm install

      - name: Build
        run: pnpm run --filter @olula/almaeventos build

      - name: Mover dist
        run: mv ./apps/almaeventos/dist ./dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.YB_DOCKERHUB_USERNAME }}
          password: ${{ secrets.YB_DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: yeboyebohub/olula_cli_almaeventos:${{ github.sha }}

  deploy-to-cluster:
    name: deploy to cluster
    if: ${{ github.ref_name == 'deploy_almaeventos' }} && ${{vars.ORGANIZATION_VAR == 'yeboyebo'}}
    runs-on: ubuntu-latest
    needs: Docker
    steps:
    
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: -n default set image --record deployment/aeproducciones-deployment appalmaeventos=yeboyebohub/olula_cli_almaeventos:${{ github.sha }}
    
    - name: verify deployment
      uses: steebchen/kubectl@v2.0.0
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.28"
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: -n default rollout status deployment/aeproducciones-deployment    
 